# Generated by CoffeeScript 1.6.3
# LOWERCASE OR IT WILL NOT WORK. Please add a function to convert to lowercase just in case.

#
#    client.getSummonerStats(summoner.acctId, function(err, result) {
#      return console.log(util.inspect(result, false, null, true));
#    });
#    client.getMatchHistory(summoner.acctId, function(err, result) {
#      return console.log(util.inspect(result, false, null, true));
#    });
#    client.getAggregatedStats(summoner.acctId, function(err, result) {
#      return console.log(util.inspect(result, false, null, true));
#    });
#    client.getTeamsForSummoner(summoner.summonerId, function(err, result) {
#      return console.log(util.inspect(result, false, null, true));
#    });
#    client.getTeamById(summoner.teamId, function(err, result) {
#      return console.log(util.inspect(result, false, null, true));
#    });
#    return client.getSummonerData(summoner.acctId, function(err, result) {
#      return console.log(util.inspect(result, false, null, true));
#    });
(->
  LolClient = undefined
  client = undefined
  options = undefined
  summoner = undefined
  util = undefined
  LolClient = require("./lol-client")
  util = require("util")
  options =
    region: "na"
    username: "username"
    password: "password"
    version: "3.15.13_12_13_16_07"

  summoner =
    name: "HotshotGG"
    acctId: 434582
    summonerId: 407750
    teamId: "TEAM-a1ebba15-986f-488a-ae2f-e081b2886ba4"

  client = new LolClient(options)
  client.on "connection", ->
    setInterval client.HeartBeat, 5000
    console.log "Connected"
    client.getSummonerByName summoner.name, (err, result) ->
      console.log util.inspect(result, false, null, true)

    return

  client.connect()
  return
).call this
